{
 "title": "Electricité",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Actuel",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT LAST_VALUE(value) OVER (ORDER BY sample_time DESC) AS \"Production\" FROM electricity_power WHERE figure='Production' LIMIT 1"
    },
    {
     "rawSql": "SELECT LAST_VALUE(value) OVER (ORDER BY sample_time DESC) AS \"Consommation\" FROM electricity_power WHERE figure='Consommation' LIMIT 1"
    }
   ]
  },
  {
   "title": "Gain si on avait été en Autoconsommation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT \n  value AS \"Economie\", sample_time\nFROM electricity_powersaving\nWHERE\n  figure='Saving'\n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()"
    },
    {
     "rawSql": "SELECT \n  value AS \"Injection\", sample_time\nFROM electricity_powersaving\nWHERE\n  figure='Injection'\n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()"
    }
   ]
  },
  {
   "title": "Compteurs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "dataset": "www",
     "rawSql": "SELECT\n  sample_time, value, metric\nFROM (\n  SELECT\n    sample_time,\n    value - LAG(value) OVER (PARTITION BY counter, figure ORDER BY sample_time) AS value,\n  CASE \n    WHEN counter = 'Production' THEN 'Production'\n    ELSE 'Consommation ' || figure \n  END AS metric\n  FROM electricity_counter\n  WHERE \n    ((counter = 'Consommation' AND figure IN ('HC', 'HP')) OR (counter = 'Production'))\n    AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()\n) sub\nWHERE value < 1500"
    }
   ]
  },
  {
   "title": "Gains sur la Facture",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT \n  value/100 AS \"Economie\", sample_time\nFROM domestik2.electricity_billing\nWHERE\n  figure='Saving'\n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()"
    },
    {
     "rawSql": "SELECT \n  value/100 AS \"Revente\", sample_time\nFROM domestik2.electricity_billing\nWHERE\n  figure='Injection'\n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()"
    }
   ]
  },
  {
   "title": "Historique des gains",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select sum(value) as \"Economie\", date(sample_time) as \"date\"\nfrom electricity_billing \nwhere\n  figure='Saving'\n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()\n group by date"
    },
    {
     "rawSql": "select\n  sum(value) as \"Economie + revente\", date(sample_time) as \"date\"\nfrom domestik2.electricity_billing\nWHERE\n  sample_time >= $__timeFrom() AND sample_time <= $__timeTo() \ngroup by date order by date;"
    },
    {
     "rawSql": "SELECT \n        DATE(sample_time) AS \"date\",\n        (MAX(value) - MIN(value))*68.355 / 1000 / 100 AS \"Revente Totale\"\nFROM domestik2.electricity_counter\nWHERE\n        counter='Production'\n        AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()\nGROUP BY date\n"
    }
   ]
  },
  {
   "title": "Puissances maximales",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "rawSql": "SELECT \n  sample_time,\n  value,\n  figure AS metric\nFROM electricity_power \nWHERE \n  figure IN ('Consommation', 'Production')\n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo()\nORDER BY sample_time"
    }
   ]
  },
  {
   "title": "Revenus de la journée",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(value) as \"Economie\" from domestik2.electricity_billing where date(sample_time) = current_date and figure='Saving';"
    },
    {
     "rawSql": "select sum(value) as \"Economie + revente\" from domestik2.electricity_billing where date(sample_time) = current_date;"
    },
    {
     "rawSql": "SELECT \n        (last - first)*68.355 / 1000 / 100 AS \"Revente Totale\"\nFROM \n( SELECT \n        LAST_VALUE(value) OVER data AS last, \n        FIRST_VALUE(value) OVER data AS first \nFROM domestik2.electricity_counter  \nWHERE  \n        DATE(sample_time) = CURRENT_DATE \nAND \n        counter='Production' \nWINDOW data AS (ORDER BY sample_time ASC) \nORDER BY sample_time DESC LIMIT 1 \n)\n"
    }
   ]
  }
 ]
}