{
 "title": "Archive électricité (brute)",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Archive des puissances consommées",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT sample_time, minimum, average, maximum\nFROM electricity_power_archive \nWHERE \n  figure = 'Consommation' \n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo() "
    }
   ]
  },
  {
   "title": "Compteur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT sample_time, increase AS \"Heure Plaine\"\nFROM electricity_counter_archive \nWHERE \n  counter = 'Consommation' \n  AND figure = 'HP'\n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo() \nORDER BY sample_time;"
    },
    {
     "rawSql": "SELECT sample_time, increase AS \"Heure Creuse\"\nFROM electricity_counter_archive \nWHERE \n  counter = 'Consommation' \n  AND figure = 'HC'\nORDER BY sample_time;"
    },
    {
     "rawSql": "SELECT sample_time, increase AS \"Production\"\nFROM electricity_counter_archive \nWHERE \n  counter = 'Production' \nORDER BY sample_time;"
    }
   ]
  },
  {
   "title": "Archive de la puissance produite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT \n  sample_time, minimum, average, maximum\nFROM electricity_power_archive \nWHERE \n  figure = 'Production' \n  AND sample_time >= $__timeFrom() AND sample_time <= $__timeTo() "
    }
   ]
  }
 ]
}