{
 "title": "Températures",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "1er",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select value AS \"Ch Amis\", sample_time FROM home_figures WHERE figure='Chambre Amis'"
    },
    {
     "rawSql": "select value AS \"Ch Joris\", sample_time FROM home_figures WHERE figure='Chambre Joris'"
    },
    {
     "rawSql": "select value AS \"Ch Océane\", sample_time FROM home_figures WHERE figure='Chambre Oceane'"
    },
    {
     "rawSql": "select value AS \"Grenier Nord\", sample_time FROM home_figures WHERE figure='Grenier Nord'"
    },
    {
     "rawSql": "select value AS \"Grenier Sud\", sample_time FROM home_figures WHERE figure='Grenier Sud'"
    }
   ]
  },
  {
   "title": "Extérieur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select value AS \"Comble\", sample_time FROM home_figures WHERE figure='Comble'"
    },
    {
     "rawSql": "SELECT value AS \"Dehors\", sample_time FROM home_figures WHERE figure='Dehors'"
    }
   ]
  },
  {
   "title": "Rdc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Bureau\", sample_time FROM home_figures WHERE figure='Bureau'"
    },
    {
     "rawSql": "SELECT value AS \"Salon\", sample_time FROM home_figures WHERE figure='Salon'"
    },
    {
     "rawSql": "SELECT value AS \"Ch Parents\", sample_time FROM home_figures WHERE figure='Chambre Parents'"
    }
   ]
  },
  {
   "title": "Sous Sol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT value as \"Cave\", sample_time FROM home_figures WHERE figure='cave'"
    },
    {
     "rawSql": "SELECT value as \"Cave Ski\", sample_time FROM home_figures WHERE figure='Cave Ski'"
    },
    {
     "rawSql": "SELECT value as \"Garage\", sample_time FROM home_figures WHERE figure='Garage'"
    },
    {
     "rawSql": "SELECT value as \"Porte Garage\", sample_time FROM home_figures WHERE figure='Porte Garage'"
    },
    {
     "rawSql": "SELECT value as \"Cave à vin\", sample_time FROM home_figures WHERE figure='Cave Vin'"
    },
    {
     "rawSql": "SELECT value as \"Buanderie\", sample_time FROM home_figures WHERE figure='Buanderie'"
    }
   ]
  }
 ]
}