{
 "title": "Power",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Actuel",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT LAST_VALUE(value) \nOVER (ORDER BY sample_time DESC) AS \"Production\" \nFROM electricity_power WHERE figure='Production' LIMIT 1"
    },
    {
     "rawSql": "SELECT LAST_VALUE(value) OVER (ORDER BY sample_time DESC) AS \"Consommation\" \nFROM electricity_power WHERE figure='Consommation' LIMIT 1"
    }
   ]
  },
  {
   "title": "Gain si on avait été en Autoconsommation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Economie\", sample_time FROM electricity_powersaving WHERE figure='Saving'"
    },
    {
     "rawSql": "SELECT value AS \"Injection\", sample_time FROM electricity_powersaving WHERE figure='Injection'"
    }
   ]
  },
  {
   "title": "Compteurs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT value - LAG(value) OVER (ORDER BY sample_time) AS Production,sample_time FROM electricity_counter WHERE counter='Production' ORDER BY sample_time ASC "
    },
    {
     "rawSql": "SELECT value - LAG(value) OVER (ORDER BY sample_time) AS \"Consommation HP\",sample_time FROM electricity_counter WHERE counter='Consommation' AND figure='HP' ORDER BY sample_time ASC \n"
    },
    {
     "rawSql": "SELECT value - LAG(value) OVER (ORDER BY sample_time) AS \"Consommation HC\",sample_time FROM electricity_counter WHERE counter='Consommation' AND figure='HC' ORDER BY sample_time ASC \n"
    }
   ]
  },
  {
   "title": "Gain sur la facture",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT value/100 AS \"Economie\", sample_time FROM domestik2.electricity_billing WHERE figure='Saving'"
    },
    {
     "rawSql": "SELECT value/100 AS \"Revente\", sample_time FROM domestik2.electricity_billing WHERE figure='Injection'"
    }
   ]
  },
  {
   "title": "Historique des gains par jour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select sum(value) as \"Economie\", date(sample_time) as \"date\"\nfrom electricity_billing \nwhere figure='Saving' group by date order by date;"
    },
    {
     "rawSql": "select sum(value) as \"Economie + revente\", date(sample_time) as \"date\"\nfrom domestik2.electricity_billing\ngroup by date order by date;"
    },
    {
     "rawSql": "SELECT \n        DATE(sample_time) AS \"date\",\n        (MAX(value) - MIN(VALUE))*68.355 / 1000 / 100 AS \"Revente Totale\"\nFROM domestik2.electricity_counter\nWHERE counter='Production'\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  {
   "title": "Puissances maximal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "rawSql": "SELECT value as Consommation,sample_time FROM electricity_power where figure='Consommation' ORDER BY sample_time ASC \n"
    },
    {
     "rawSql": "SELECT value as Production,sample_time FROM electricity_power where figure='Production' ORDER BY sample_time ASC \n"
    }
   ]
  },
  {
   "title": "Revenus de la journée",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(value) as \"Economie\" from domestik2.electricity_billing \nwhere date(sample_time) = current_date and figure='Saving';"
    },
    {
     "rawSql": "select sum(value) as \"Economie + revente\" \nfrom domestik2.electricity_billing where date(sample_time) = current_date;"
    },
    {
     "rawSql": "SELECT \n        (last - first)*68.355 / 1000 / 100 AS \"Revente Totale\"\nFROM \n( SELECT \n        LAST_VALUE(value) OVER data AS last, \n        FIRST_VALUE(value) OVER data AS first \nFROM domestik2.electricity_counter  \nWHERE  \n        DATE(sample_time) = CURRENT_DATE \nAND \n        counter='Production' \nWINDOW data AS (ORDER BY sample_time ASC) \nORDER BY sample_time DESC LIMIT 1 \n) AS t\n"
    }
   ]
  }
 ]
}