Electricité.icon: /usr/share/icons/elementary/status/48/battery-ac-adapter.svg
Electricité.style.fill: "#f9e79f"
Electricité.*.style.fill: "#f4d03f"
Electricité.*.*.style.fill: "#f1c40f"
Electricité.Compteurs.icon: /home/laurent/Projets/Domestik/ressources/Compteur.png
Electricité.Puissance.icon: /home/laurent/Projets/Domestik/ressources/Puissance.svg
Electricité.Economie.icon: /home/laurent/Projets/Domestik/ressources/Economie.png
Electricité.Facture.icon: /home/laurent/Projets/Domestik/ressources/Euro.png
