Machines.icon: /usr/share/icons/elementary/devices/48/computer-laptop.svg
# Machines.style.fill: "#f9e79f"
Machines.style.fill: "#d0ffff"
Machines.*.style.fill: "#b0ffff"
# Machines.*.*.style.fill: "#40ffff"

